# Generated by Django 5.0.6 on 2024-08-24 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_livesession_public_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LiveSession',
        ),
    ]
