# Generated by Django 5.0.6 on 2024-07-04 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_profile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='institute',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
