# Generated by Django 5.0.6 on 2024-07-04 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_profile_institute'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='email',
            new_name='profile_email',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='username',
            new_name='profile_username',
        ),
    ]
